name: next-week-us-markets-events
on:
  schedule:
    - cron: "0 14 * * 0"   # Sundays 10:00 AM ET (14:00 UTC during EDT)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    environment: POLYGON_API_KEY
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python poster.py us-markets-next-week-events
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          X_CONSUMER_KEY: ${{ secrets.X_CONSUMER_KEY }}
          X_CONSUMER_SECRET: ${{ secrets.X_CONSUMER_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          DRY_RUN: ${{ vars.DRY_RUN }}
